### ISSUE TITLE
No point cloud when Play the rosbag

### ISSUE THREAD

**Issue by SekiroRong** [zfc-zfc/IDAT7213_Project#2]
Hi, I came across another problem when trying the 4.3 step in the guideline (Play the rosbag). And here's a screenshot of my output:

![圖片](https://user-images.githubusercontent.com/64967662/232205641-e86daa31-ca83-41d1-a131-7f9eb72866ca.png)

There's no point cloud in the GUI, which is different from the guideline and I think it's not normal. Do you have any Idea to solve this?

Thank you very much.

**Comment by SekiroRong** [comment]
And got a log like this:
```
[ WARN] [1681550722.950162533]: FAST-LIO not ready, no points stored.
[ INFO] [1681550723.049893342]: IMU Initializing: 73.0 %
[ WARN] [1681550723.049944564]: FAST-LIO not ready, no points stored.
[ INFO] [1681550723.150857115]: IMU Initializing: 87.0 %
[ WARN] [1681550723.150900290]: FAST-LIO not ready, no points stored.
[ INFO] [1681550723.251271779]: IMU Initializing: 95.5 %
[ INFO] [1681550723.251329213]: IMU Initialization Done: Gravity: -0.0000 -0.0000 9.8100, Acc norm: 9.8000
[ INFO] [1681550723.251342129]: IMU Initialization Done: Gyro_bias: -0.0000, 0.0000, -0.0000
[ WARN] [1681550723.251454733]: FAST-LIO not ready, no points stored.
```
![圖片](https://user-images.githubusercontent.com/64967662/232206968-c1c6504f-e02b-45a7-bb58-5119a678891f.png)

**Comment by zfc-zfc** [comment]
> Hi, I came across another problem when trying the 4.3 step in the guideline (Play the rosbag). And here's a screenshot of my output:
> 
> ![圖片](https://user-images.githubusercontent.com/64967662/232205641-e86daa31-ca83-41d1-a131-7f9eb72866ca.png)
> 
> There's no point cloud in the GUI, which is different from the guideline and I think it's not normal. Do you have any Idea to solve this?
> 
> Thank you very much.

Please refer to the latest version of guideline (Page 52-53).

**Comment by SekiroRong** [comment]
Thank you for your reply. Actually, I've tried the solution provided in guideline (Page 52), even though I didn't come across that particular error. However, I still can't find any point cloud after playing the rosbag.

**Comment by zfc-zfc** [comment]
> 

Other student who came across the same problem has already fixed it by following pages 52-53 of the latest guideline. If you still cannot solve that, you could bring your laptop and come to LG02 of the HW Building for help.
![image](https://user-images.githubusercontent.com/50921331/233415217-d26f6212-c6f9-41fe-9590-d0a059c8067d.png)

**Comment by SekiroRong** [comment]
> > 
> 
> 
> 
> Other student who came across the same problem has already fixed it by following pages 52-53 of the latest guideline. If you still cannot solve that, you could bring your laptop and come to LG02 of the HW Building for help.
> 
> ![image](https://user-images.githubusercontent.com/50921331/233415217-d26f6212-c6f9-41fe-9590-d0a059c8067d.png)
> 
> 

Thank you for your reply. Actually, I reinstalled Ubuntu and gone through the process again and it worked.
